### PR TITLE
Refactor(YoloSimulation): Run Simulation as separate process

### PR DESCRIPTION
**Pull request by vsaw**
This pull request changes YoloSimulation behaviour by creating a new YoloSimulation subprocess.

This allows us to run the regular YoloDarknet code even in simulation, as opposed to replacing it with a mock YoloDarknet object as before.

# PR Notes

This PR is based on https://github.com/vsaw/opendatacam which includes the following pending PRs

- #284
- #287
- #289
- #291
- #293
- #299
- https://github.com/opendatacam/opendatacam/pull/301

It is therefore recommended to merge this **after** merging the PRs above.

### CODE REVIEW

**Comment by vsaw** [comment]
Waiting for #301 to be merged. Then we can look at this one.

**Comment by vsaw** [comment]
Now that all dependencies are merged in develop this is good for review :-)

**Comment by tdurand** [comment]
I quickly had a look, looks good but when I try it by doing this:

- pulling this PR
- Setting "simulation" in config.json "VIDEO_INPUT"
- `npm run dev`

I get this error: 

```
Projects/opendatacam/server/processes/YoloDarknet.js:50
    var initialCommand = [this.config.darknetCmd, 'detector', 'demo', this.config.yoloParams.data, this.config.yoloParams.cfg, this.config.yoloParams.weights];
                                                                                             ^

TypeError: Cannot read property 'data' of undefined
```

Didn't try to investigate, can you reproduce ? 

Also we should had a note in the documentation about the simmulation mode .. maybe here: https://github.com/opendatacam/opendatacam/blob/master/documentation/DEVELOPMENT_NOTES.md ?

**Comment by vsaw** [comment]
@tdurand Your error is expected as you did not select a neural network, just like with "real Darknet" :-)

Regarding the documentation. Sure, I'll try to write a few lines. If you want to beat me to it, the PR is now open for contributions from you :-)

**Comment by tdurand** [comment]
ok, could we easily make this optional ? just needing to put VIDEO_INPUT: simulation ? Because it is a bit misleading to specify a neural network if it actually take the frames from the simulation

Now I run into another problem, with this config:


```
"OPENDATACAM_VERSION": "3.0.1",
  "PATH_TO_YOLO_DARKNET" : "TO_REPLACE_PATH_TO_DARKNET",
  "CMD_TO_YOLO_DARKNET" : "TO_REPLACE_PATH_TO_DARKNET/darknet",
  "VIDEO_UPLOAD_FOLDER": "TO_REPLACE_PATH_TO_DARKNET/opendatacam_videos_uploaded",
  "VIDEO_INPUT": "simulation",
  "NEURAL_NETWORK": "yolov4",
  "VIDEO_INPUTS_PARAMS": {
    "file": "opendatacam_videos/demo.mp4",
    "usbcam": "v4l2src device=/dev/video0 ! video/x-raw, framerate=30/1, width=640, height=360 ! videoconvert ! appsink",
    "raspberrycam": "nvarguscamerasrc ! video/x-raw(memory:NVMM),width=1280, height=720, framerate=30/1, format=NV12 ! nvvidconv ! video/x-raw, format=BGRx, width=640, height=360 ! videoconvert ! video/x-raw, format=BGR ! appsink",
    "remote_cam": "YOUR IP CAM STREAM (can be .m3u8, MJPEG ...), anything supported by opencv",
    "remote_hls_gstreamer": "souphttpsrc location=http://YOUR_HLSSTREAM_URL_HERE.m3u8 ! hlsdemux ! decodebin ! videoconvert ! videoscale ! appsink",
    "simulation": "--yolo_json public/static/placeholder/alexeydetections30FPS.json --video_file_or_folder public/static/placeholder/frames --isLive true --jsonFps 20 --mjpgFps 0.2"
  }
```

I get infinite:

```
Restart YOLO
Missing required argument: yolo_json

Options:
  --help                  Show help                                    [boolean]
  --version               Show version number                          [boolean]
  --yolo_json                                                         [required]
  --video_file_or_folder                                           [default: ""]
  --isLive                                             [boolean] [default: true]
  --jsonFps                                               [number] [default: 20]
  --mjpgFps                                               [number] [default: 20]
  --darknetStdout                                      [boolean] [default: true]
  --json_port                                           [number] [default: 8070]
  --mjpeg_port                                          [number] [default: 8090]
Restart YOLO
Missing required argument: yolo_json
```

**Comment by vsaw** [comment]
We could provide "dummy" weights, data and config if no network is specified. A good point to do this would be here: https://github.com/opendatacam/opendatacam/pull/302/files#diff-a4c65ede64197e1a112899a68bf994485b889c4b143198bac4af53425b38406fR57-R60

As for your error. I'm a bit baffled. Can you provide more detiails? And does `npm test` work for you?

**Comment by tdurand** [comment]
npm test result, get the same but the test pass

```
.YoloDarknet: Empty configuration passed, most likely because you are in Simulation mode.
Process YOLO initialized
YoloSimulation {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  isStarting: false,
  isStarted: false,
  isInitialized: true,
  process: null,
  videoResolution: { w: 0, h: 0 },
  config: {
    videoParams: {
      yolo_json: '/home/tdurand/Documents/Projects/opendatacam/public/static/placeholder/alexeydetections30FPS.json',
      video_file_or_folder: '/home/tdurand/Documents/Projects/opendatacam/public/static/placeholder/frames',
      isLive: false,
      jsonFps: 20,
      mjpgFps: 0.2
    },
    jsonStreamPort: 8070,
    mjpegStreamPort: 8090,
    simulationStartupDelayMs: 0,
    darknetStdout: false
  },
  isVideoDirectory: true,
  videoFileOrFolderExists: true,
  videoFileFps: null,
  detections: [
    { frame_id: 16, objects: [Array] },
    ... 337 more items
  ],
  simulationMJPEGServe: null,
  simulationJSONHTTPStreamServer: null,
  [Symbol(kCapture)]: false
}
Missing required argument: yolo_json

Options:
  --help                  Show help                                    [boolean]
  --version               Show version number                          [boolean]
  --yolo_json                                                         [required]
  --video_file_or_folder                                           [default: ""]
  --isLive                                             [boolean] [default: true]
  --jsonFps                                               [number] [default: 20]
  --mjpgFps                                               [number] [default: 20]
  --darknetStdout                                      [boolean] [default: true]
  --json_port                                           [number] [default: 8070]
  --mjpeg_port                                          [number] [default: 8090]
.Process YOLO initialized
.Process YOLO initialized
Process YOLO started
Video stream: 1280x720
.


8 specs, 0 failures
Finished in 0.301 seconds
```

For the bug, to try to reproduce, try checkout this PR and put this in config :

```
"OPENDATACAM_VERSION": "3.0.1",
  "PATH_TO_YOLO_DARKNET" : "TO_REPLACE_PATH_TO_DARKNET",
  "CMD_TO_YOLO_DARKNET" : "TO_REPLACE_PATH_TO_DARKNET/darknet",
  "VIDEO_UPLOAD_FOLDER": "TO_REPLACE_PATH_TO_DARKNET/opendatacam_videos_uploaded",
  "VIDEO_INPUT": "simulation",
  "NEURAL_NETWORK": "yolov4",
  "VIDEO_INPUTS_PARAMS": {
    "file": "opendatacam_videos/demo.mp4",
    "usbcam": "v4l2src device=/dev/video0 ! video/x-raw, framerate=30/1, width=640, height=360 ! videoconvert ! appsink",
    "raspberrycam": "nvarguscamerasrc ! video/x-raw(memory:NVMM),width=1280, height=720, framerate=30/1, format=NV12 ! nvvidconv ! video/x-raw, format=BGRx, width=640, height=360 ! videoconvert ! video/x-raw, format=BGR ! appsink",
    "remote_cam": "YOUR IP CAM STREAM (can be .m3u8, MJPEG ...), anything supported by opencv",
    "remote_hls_gstreamer": "souphttpsrc location=http://YOUR_HLSSTREAM_URL_HERE.m3u8 ! hlsdemux ! decodebin ! videoconvert ! videoscale ! appsink",
    "simulation": "--yolo_json public/static/placeholder/alexeydetections30FPS.json --video_file_or_folder public/static/placeholder/frames --isLive true --jsonFps 20 --mjpgFps 0.2"
  }
```

Then do

```
npm i
npm run build
npm run start

// or npm run dev 
```

And then when you open the localhost:8080 you get infinite message

```
Missing required argument: yolo_json

Options:
  --help                  Show help                                    [boolean]
  --version               Show version number                          [boolean]
  --yolo_json                                                         [required]
  --video_file_or_folder                                           [default: ""]
  --isLive                                             [boolean] [default: true]
  --jsonFps                                               [number] [default: 20]
  --mjpgFps                                               [number] [default: 20]
  --darknetStdout                                      [boolean] [default: true]
  --json_port                                           [number] [default: 8070]
  --mjpeg_port                                          [number] [default: 8090]
Restart YOLO
Missing required argument: yolo_json
```

**Comment by vsaw** [comment]
Thanks! The output of `npm test` is fine as I do not intercept stdout.

I really don't understand why this does not work. Can you try the following in your repository root:

```bash
node scripts/YoloSimulation.js --yolo_json public/static/placeholder/alexeydetections30FPS.json --video_file_or_folder public/static/placeholder/frames --isLive true --jsonFps 20 --mjpgFps 0.2
```

This should tell us if there's something wrong with the script or the way how YoloDarknet invokes it...

Thanks again for your debugging!

**Comment by tdurand** [comment]
no problem.. sorry I didn't look into the code still ;-)

```bash
node scripts/YoloSimulation.js --yolo_json public/static/placeholder/alexeydetections30FPS.json --video_file_or_folder public/static/placeholder/frames --isLive true --jsonFps 20 --mjpgFps 0.2
```

```
YoloSimulation Start with Arguments
{
  videoParams: {
    yolo_json: 'public/static/placeholder/alexeydetections30FPS.json',
    video_file_or_folder: 'public/static/placeholder/frames',
    isLive: true,
    jsonFps: 20,
    mjpgFps: 0.2
  },
  jsonStreamPort: 8070,
  mjpegStreamPort: 8090,
  darknetStdout: true
}
YoloDarknet: Empty configuration passed, most likely because you are in Simulation mode.
Process YOLO initialized
YoloSimulation {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  isStarting: false,
  isStarted: false,
  isInitialized: true,
  process: null,
  videoResolution: { w: 0, h: 0 },
  config: {
    videoParams: {
      yolo_json: '/home/tdurand/Documents/Projects/opendatacam/public/static/placeholder/alexeydetections30FPS.json',
      video_file_or_folder: '/home/tdurand/Documents/Projects/opendatacam/public/static/placeholder/frames',
      isLive: true,
      jsonFps: 20,
      mjpgFps: 0.2
    },
    jsonStreamPort: 8070,
    mjpegStreamPort: 8090,
    simulationStartupDelayMs: 5000,
    darknetStdout: true
  },
  isVideoDirectory: true,
  videoFileOrFolderExists: true,
  videoFileFps: null,
  detections: [
    { frame_id: 16, objects: [Array] },
    ... 337 more items
  ],
  simulationMJPEGServe: null,
  simulationJSONHTTPStreamServer: null,
  [Symbol(kCapture)]: false
}
Video stream: 1280x720
Start HTTP JSON Stream server
undefined
Start MJPEG server
```

There is an `undefined`

Also running with node v12

**Comment by tdurand** [comment]
Can't you reproduce on your end ?

**Comment by vsaw** [comment]
Yeah I can reproduce now. Don't really know why this broke now but at least I found where it broke. Will update the PR.

**Comment by vsaw** [comment]
@tdurand it should be fixed now. Please test again, and be aware that running `npm run dev` will most likely fail until https://github.com/opendatacam/opendatacam/issues/313 is fixed

**Comment by tdurand** [comment]
works great, and thanks for the documentation !

**Pull request merged**
