### PR TITLE
Feature use env variables

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**
This PR adds:

[dotenv](https://www.npmjs.com/package/dotenv) as dependency so we can load values like the mongodb url and ports not only from the `config.json` but also from environment variables. This would allow us to use the [environment section](https://docs.docker.com/compose/environment-variables/) of a container for configuration or even a [.env file](https://docs.docker.com/compose/env-file/) in docker-compose.yml. 

Currently the call to `dotenv` is located in `server/util/configHelper.js` which is fine but could also be used on package.json scripts section like so:
```json
{
	"scripts":{
		"dev": "node -r dotenv/config server.js"
	}
}
```
This is up to you @tdurand 

It also adds a some tests for the new functions in `configHelper.js` to be a little more sure that they work.

These tests can be called like this:
bash & zsh
```bash
MONGODB_URL=foo \
PORT_APP=1234 \
PORT_DARKNET_MJPEG_STREAM=1234 \
PORT_DARKNET_JSON_STREAM=1234 \
node server/utils/configHelper.test.js
```

fish shell:

```fish
env MONGODB_URL=foo \
env PORT_APP=1234 \
env PORT_DARKNET_MJPEG_STREAM=1234 \
env PORT_DARKNET_JSON_STREAM=1234 \
node server/utils/configHelper.test.js
```

These test mimic the use of jest. For future contributions it would be great to have a testing framework, but for now this is fine.

---

Edit: Prettier snuck in some formatting on the `DBManager.js`. The actual change is only in the head where the mongodb Url is loaded from the config.json. This was exchanged with a new function from the helpers which checks also for the env variables

---

Edit: Add section about environment variables to CONFIG.md

### CODE REVIEW

**Comment by tdurand** [comment]
Thanks ! Will merge this tomorrow, looks good to me

**Comment by tdurand** [comment]
Could you add some documentation in the CONFIG.md file  ?  maybe create a section in the advanced settings ? https://github.com/opendatacam/opendatacam/blob/master/documentation/CONFIG.md#advanced-settings

**Comment by fabianmoronzirfas** [comment]
@tdurand done. Please take a look.

**Comment by tdurand** [comment]
perfect, thanks for taking the time !

**Comment by fabianmoronzirfas** [comment]
awesome!

**Pull request merged**
