### PR TITLE
refactor(Docker): Uses pre-built Darknet

### LINKED ISSUE #358: CI/CD: Use pre-build Opendatacam Darknet Images
Currently the CI/CD pipeline builds https://github.com/opendatacam/darknet from source every time. As Darknet is not going through many changes we could create a Darknet Docker Image for Opendatacam and then use this image directly.

It should cut off approx 5 minutes of execution time from the Workflow.

# See also

- https://github.com/opendatacam/opendatacam/pull/354

### PR DESCRIPTION
**Pull request by vsaw**
Refactoring to speed up our Docker image build time.

Closes #358

### CODE REVIEW

**Comment by tdurand** [comment]
🙌

**Comment by vsaw** [comment]
With the pre-build Darknet, the CI took 13 minutes to run. A significant improvement to before (~25 minutes)!

I will now merge and validate that the image is still functional.

**Comment by tdurand** [comment]
> Update
> At some point I would love to store the build artifacts of the PR runs (or run tests on the final docker image) so I can verify things without pushing to dockerhub first...

Not sure I got it, what does it mean ?

**Comment by vsaw** [comment]
Every Pull-Request builds a docker image, which we do not store. (We only check if the build succeeds). We only store/publish the docker images once the pull request was merged into development.

At some point I would either store the docker image generated by the pull request check before it got merged so I can verify the docker image. Alternatively we could try to run the docker image as part of the check and verify it's functionality automatically.

**Comment by tdurand** [comment]
ok, well if somehow you can make it to store the docker image or the particular PR and then to delete it automatically when the PR get merged.. would work 😁

**Comment by vsaw** [comment]
Github has the option to store "artifacts" for every action it runs. Those get deleted automatically after a certain time (I believe the default is 90 days). See screenshot below from this action run https://github.com/opendatacam/opendatacam/actions/runs/487622871

image

I just have not yet gotten around looking into this :-)

**Comment by tdurand** [comment]
okay ! well yes might be a good thing, store "temp" build on github, and more "release" ones on dockerhub .. Anyways, let me know if you need anything 😉

**Comment by vsaw** [comment]
Exactly, that's the plan. Only what gets merged into development goes to Docker. Everything else stays in GitHub. I will let you know if I get to work on that.

**Pull request merged**
