### PR TITLE
refactor(components): Ran eslint --fix on all components

### PR DESCRIPTION
**Pull request by vsaw**

### CODE REVIEW

**Comment by tdurand** [comment]
@vsaw OK ! please go ahead, there is still two conflicts (I think cause by merging the DB refactoring) .. just merge after your solve them

**Comment by vsaw** [comment]
@tdurand you are right those come from the DB refactoring, but they were easy fixes!

**Comment by tdurand** [comment]
looking forward to be able to review pull request without syntax noise 😂

**Comment by vsaw** [comment]
> looking forward to be able to review pull request without syntax noise 😂

Me too! I'll slowly run all files through `eslint --fix` which according to `eslint` should remove 1449 warnings. (Unfortunately this will still leave us with 1318 warnings that we have to fix manually 😩)

**Pull request merged**
