### PR TITLE
Fix incorrect path

### PR DESCRIPTION
**Pull request by munsterlander**
A default install will fail due to the path being incorrect. This also does not address that the demo file that is mentioned is not saved in the directory, so probably need to fix that too or get clarification if that is not supposed to be there.

### CODE REVIEW

**Comment by vsaw** [comment]
I have not tested this yet, but I have a feeling it might break the docker builds because we download the demo video in the `opendatacam_videos` folder and not `opendatacam_videos_uploaded`

See also https://github.com/opendatacam/opendatacam/blob/development/docker/build/nano/Dockerfile#L14

**Comment by munsterlander** [comment]
Ok, do you want me to update that file and the others (docs, tests, etc) because without that directory fix, it throws a ton of errors for non docker builds OR should the directory just not have _uploaded on it so everything else stays the same?

**Comment by vsaw** [comment]
I think it makes sense to add `_uploaded` everywhere to keep things consistent.

**Comment by munsterlander** [comment]
Can do! Give me a bit but I will update this branch / pr with all the relevant locations.

**Comment by vsaw** [comment]
Actually I was going through the docs and everything again and am now confused I don't understand the issue you had in the first place. Could you please explain one more time what was happening to you and why you'd like to change the paths?

**Comment by munsterlander** [comment]
Ok, fairly simple issue - at least I think so (maybe I am way off on this) - but with a default install of the `development` branch and doing a non-docker install, the default file path is: `"file": "opendatacam_videos/demo.mp4",`.  This file does not exist and the only folder already created, is the `opendatacam_videos_uploaded` folder - which should be for dropped videos, right?  I assumed ODC would be treating the demo video as if it was dropped and because that folder exists, I figured the paths should be updated and we just needed to drop the demo.mp4 in there.  Maybe not though and the instructions should just be to create `opendatacam_videos` folder and copy the file there or wherever you want the demo video to be in the darknet folder.

**Pull request closed without merging**
