### PR TITLE
fix(YOLO): use proper JSON parser

### PR DESCRIPTION
**Pull request by mildsunrise**
The parser we have now is very fragile... it relies on the application emitting one JSON message in every chunk, and it relies on those chunks arriving exactly the same. Applications should **never** do that, i.e. the network stack can concatenate chunks, split them, etc. Furthermore this breaks on the first message since it has an opening `[`. Also, this calls `chunk.toString()` on every chunk which can result in corrupted text.

Instead, use a JSON streaming parser like [stream-json](https://github.com/uhop/stream-json). It's way more robust and simplifies the code a lot.

### CODE REVIEW

**Review by vsaw — APPROVED** [review]

**Comment by tdurand** [comment]
Very nice, and sorry for the archaic first implementation , I didn't know about much about more robust way to handle this.

I just tried it but for some reason in Simulation mode I get an infinite

```
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
Got request on JSON Stream server started
Got first JSON chunk
```

Didn't get the time to investigate further , maybe you can have a look ?

**Comment by mildsunrise** [comment]
will investigate, and I also have to rebase this

**Comment by tdurand** [comment]
I just did the rebase ;-)

**Comment by mildsunrise** [comment]
I see... the reason it fails is because the parser expects an array of objects:

~~~
[ {object1}, {object2}, {object3}, ...
~~~

But `YoloSimulation.js` [sends the objects directly](https://github.com/opendatacam/opendatacam/blob/d911374a280692eb213ff61523d56f6a7de8a49b/server/processes/YoloSimulation.js#L280):

~~~
{object1} {object2} {object3}
~~~

We should make the format consistent. Darknet uses the first one, right?

**Comment by tdurand** [comment]
yes let's make it consistent.. maybe @vsaw can help with this also , thanks for looking into it

**Comment by mildsunrise** [comment]
done, simulation should work now

**Comment by tdurand** [comment]
🎊️ very nice thanks !

I love how this gets rid of very hacky code ;-)

**Comment by vsaw** [comment]
@mildsunrise @tdurand Great catch. Sorry if I missed this in my refactoring 👍

**Pull request merged**
