### PR TITLE
Add support for Kubernetes

### PR DESCRIPTION
**Pull request by paroque28**
The changes refactor the installation script and add all the Kubernetes YAML files.

Tested on Jetson Nano with K3S + Nvidia Container Runtime (Kubernetes for embedded).

Logs:
```
Length: 1142 (1.1K) [text/plain]
Saving to: 'opendatacam/0001-mongodb-deployment.yaml'

0001-mongodb-deployment.ya 100%[======================================>]   1.12K  --.-KB/s    in 0s      

Last-modified header missing -- time-stamps turned off.
2020-07-17 03:32:40 (14.7 MB/s) - 'opendatacam/0001-mongodb-deployment.yaml' saved [1142/1142]

--2020-07-17 03:32:40--  https://raw.githubusercontent.com/paroque28/opendatacam/master/docker/run/nano/0002-opendatacam-deployment.yaml
Resolving raw.githubusercontent.com... 199.232.0.133
Connecting to raw.githubusercontent.com|199.232.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1372 (1.3K) [text/plain]
Saving to: 'opendatacam/0002-opendatacam-deployment.yaml'

0002-opendatacam-deploymen 100%[======================================>]   1.34K  --.-KB/s    in 0s      

Last-modified header missing -- time-stamps turned off.
2020-07-17 03:32:41 (9.33 MB/s) - 'opendatacam/0002-opendatacam-deployment.yaml' saved [1372/1372]

W0717 03:32:42.113772  905811 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
configmap/opendatacam configured
service/opendatacam-mongo unchanged
persistentvolumeclaim/mongodb-pv-claim unchanged
deployment.apps/opendatacam-mongo configured
service/opendatacam unchanged
deployment.apps/opendatacam unchanged
NAME                                                         READY   STATUS    RESTARTS   AGE
gpu-operator-node-feature-discovery-worker-v77gq             1/1     Running   44         29d
gpu-operator-677b9c86bf-2pkfj                                1/1     Running   21         29d
gpu-operator-node-feature-discovery-master-fbf955747-2f885   1/1     Running   21         29d
svclb-opendatacam-vbbrn                                      3/3     Running   0          3h46m
opendatacam-mongo-75c8dd6f69-qcqcq                           1/1     Running   0          3h35m
opendatacam-65c4cc846b-x67l8                                 1/1     Running   0          3m43s
NAME                                         TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                                        AGE
kubernetes                                   ClusterIP      10.43.0.1      <none>           443/TCP                                        29d
gpu-operator-node-feature-discovery-master   ClusterIP      10.43.54.117   <none>           8080/TCP                                       29d
opendatacam                                  LoadBalancer   10.43.186.42   192.168.100.44   8080:32496/TCP,8070:31915/TCP,8090:31175/TCP   3h46m
opendatacam-mongo                            ClusterIP      10.43.60.126   <none>           27017/TCP                                      3h35m
OpenDataCam docker container installed successfully, it might take up to 1-2 min to start the node app and the webserver
wlan0: error fetching interface information: Device not found
Ethernet device IP
OpenDataCam is available at: http://192.168.100.44:8080
OpenDataCam will start automaticaly on boot when you restart you jetson
If you want to stop it, please refer to the doc: https://github.com/opendatacam/opendatacam
```

I would upload a screenshot but is the same as with Docker-compose

### CODE REVIEW

**Comment by tdurand** [comment]
Hi, 

Thanks.. I have 0 experience with Kubernetes so I have some questions

Questions:

- Does this changes the default install command: `./install-opendatacam.sh --platform nano` ? 
- Could you put the kubernetes files inside a dedicated folder like:  `docker/run/desktop/kubernetes`  so it is a bit more separated ?
- Could you add documentation  how to install OpenDataCam using Kubernetes ?

**Comment by paroque28** [comment]
Hello,

> Does this changes the default install command: ./install-opendatacam.sh --platform nano ?
No, I have set docker-compose as the default orchestrator.

```
if [ "$ORCHESTRATOR" == "" ] || [ -z "$INDEX" ]
  then
    ORCHESTRATOR="docker-compose"
fi
```

>  Could you put the Kubernetes files inside a dedicated folder like: docker/run/desktop/kubernetes so it is a bit more separated ?

Yes, I can!

>  Could you add documentation on how to install OpenDataCam using Kubernetes?

And yes I also can!

I will update this pull request later.

Thanks

**Comment by paroque28** [comment]
Done!
Note that I am assuming this link that includes the version. So it will work until next release
```
wget -N https://raw.githubusercontent.com/opendatacam/opendatacam/$VERSION/docker/run/$PLATFORM/kubernetes/0001-mongodb-deployment.yaml -P opendatacam
wget -N https://raw.githubusercontent.com/opendatacam/opendatacam/$VERSION/docker/run/$PLATFORM/kubernetes/0002-opendatacam-deployment.yaml -P opendatacam
```

**Comment by tdurand** [comment]
Thanks ! I will merge this only with the next version as otherwise as you said it won't work.. But right now we are in summer break so it will take a bit of time to do it... 

Anyways if people are interested they can have a look  at your PR

**Comment by paroque28** [comment]
Would it be good for you if I change the references to master for now?
And then later, when the next version is available,  change them back to $VERSION.
Because even when the next version is ready for release, we would need to modify these files to change the container version number:
```
spec:
      containers:
      - image: opendatacam/opendatacam:v3.0.1-platform
```
I will add the commit just in case

**Comment by tdurand** [comment]
Ok, I understand, I merge this.. let's hope we don't forget then to replace them.. adding a not on the DEVELOPMENT NOTE : https://github.com/opendatacam/opendatacam/commit/761d10ef6c9e129f8c3905a99c47534791a83dbf

The release process for OpenDataCam is very manual unfortunately .

**Pull request merged**
