### PR TITLE
some nits in mjpeg-proxy

### PR DESCRIPTION
**Pull request by mildsunrise**
`chunk` is already a buffer, so the conversion isn't needed :)

also, change `http.request()` + `request.end()` to an `http.get()` call

### CODE REVIEW

**Comment by tdurand** [comment]
Didn't tell you on the other issue, but could you do the PRs on the `development` branch ?

**Comment by mildsunrise** [comment]
sure! no problem

**Comment by tdurand** [comment]
Is this still relevant to merge @mildsunrise  ? thanks

**Comment by mildsunrise** [comment]
yes, it doesn't hurt

**Pull request merged**
