### PR TITLE
Feat: Update to NextJS 10

### PR DESCRIPTION
**Pull request by vsaw**
Next v9 was getting a bit old and Next 10 could be upgraded to without
any breaking changes according to https://nextjs.org/docs/upgrading#upgrading-from-version-9-to-10

See also #485

### CODE REVIEW

**Comment by vsaw** [comment]
@munsterlander This fixes the caniuse warnings for me. A quick test with the simulation showed no issues. Let me know if you experience any.

**Comment by munsterlander** [comment]
@vsaw That removed the warning. :th

**Comment by vsaw** [comment]
Great! I've updated my docker image fork with Next 10. You can find it [here](https://hub.docker.com/r/vsawdoteu/opendatacam/tags) in a few minutes when the github action has finished running. Do you have to option to test it quickly for me? I'm currently travelling and dont have any jetson HW with me.

**Comment by vsaw** [comment]
Have you added styled-jsx to you package.json? This now needs to be explicitly included.

**Comment by munsterlander** [comment]
NOPE!  That would probably be the reason.  I will add that and see what happens.  My other branch has that, so I just failed to bring that over.

**Pull request merged**
