### PR TITLE
Refactor: Better Database abstraction

### LINKED ISSUE #345: Refactor: Better Database abstraction
From https://github.com/opendatacam/opendatacam/issues/337

> Database Abstraction. At the moment all code accesses the MongoDB Abstraction directly, which makes it difficult to change to different persistence as currently being developed in the [evo-addnedbconnector](https://github.com/opendatacam/opendatacam/tree/evo-addnedbconnector) branch

### PR DESCRIPTION
**Pull request by vsaw**
This code improves Opendatacams ability to use different database by cleaning up the database abstraction. Key improvements in this pull request are

1. The current Database is renamed to `MongoDbManager` and an abstract `DbManagerBase` class was introduced
2. The database is set up in the beginning of `server.js` and then passed as a variable into Opendatacam based on the values in `config.json`
3. The Recording ID is not longer auto-generated by MongoDB. Instead a random [RFC4122](https://www.ietf.org/rfc/rfc4122.txt) compliant UUID is created by Opendatacam
1. No `eslint` warnings in `server/db`or `server/model` anymore 😙

Closes #345

### CODE REVIEW

**Comment by vsaw** [comment]
@tdurand The refactoring turned out a bit more extensive then expected but it should be finished now. Would you please review to make sure I did not miss anything.

**Comment by tdurand** [comment]
Great ! will do next week ! Happy 🎄 !

**Comment by vsaw** [comment]
> Great ! will do next week ! Happy 🎄 !

No rush! It should hopefully make your mobile-db version easier to develop and merge.

Happy holidays 🎄

**Comment by tdurand** [comment]
Seems perfect !! thanks for this ! (I didn't test yet, but will merge and we can fix afterwise if it introduce some bugs)

**Pull request merged**
