### PR TITLE
Build Docker Images using GitHub Actions

### LINKED ISSUE #211: Move docker build process to the cloud
I was wondering if it would be possible to build the entire docker image for the ODC on a cloud platform / not on the device itself.

Generally docker offers the feature to build ARM based images on a x86 machine. (https://www.docker.com/blog/multi-arch-images/)
StereoLabs is already doing something similar (https://www.stereolabs.com/docs/docker/building-arm-container-on-x86/).

Maybe we can use  GitHub Actions to automate this, which would be a super nice feature when it comes to patching stuff etc.

What do you think @tdurand ?

### PR DESCRIPTION
**Pull request by vsaw**
# Goal

This is a work in progress pull request with the goal to 

- add our docker build setup to our Continuous Integration setup
- publish Opendatacam development previews to dockerhub

# Status

The following things are implemented in this pull request (or still to be implemented)

- [x] Build Opendatacam docker image from local source
- [x] Adds docker build to Opendatacam's CI/CD
- [x] Push development build to dockerhub
    - [x] Generate Dockerhub API key to use in the action
    - [x] Update the action
- [x] Verify the development preview is working by running it on a Jetson device
- [x] Update docker build documentation

Since the build takes approx 20 minutes we could to the following to speed it up. However this might be part of a separate pull request

- [ ] Speed up docker build process by using a pre-built https://github.com/opendatacam/darknet
- [ ] Cache download of the weights
- [ ] Implement Docker Cache either locally or from registry

Also this only covers development previews. Mayor releases still need to be done manually.

- [ ] Docker build on new git release/tag

# See also

Closes #211

### CODE REVIEW

**Comment by vsaw** [comment]
@tdurand @b-g In order to push the development build to docker hub I would need your assistance. You would need to setup a Secret in this repository for the action to access dockerhub.

The required secrets are `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`. (See https://docs.docker.com/docker-hub/access-tokens/ how to create tokens).

Let me know when you have added the secrets to the opendatacam repository. Then I will continue with the pull-request.

**Comment by tdurand** [comment]
Looking into it now !

**Comment by tdurand** [comment]
Here is what I have done, let me know if something is missing:

Github actions settings to allow only action from within opendatacam org:

image


Access tokens on dockerhub

image


Repository secrets:

image

**Comment by vsaw** [comment]
> Here is what I have done, let me know if something is missing:
> 
> 
> 
> Github actions settings to allow only action from within opendatacam org:
> 
> 
> 
> image

That was not what I meant. This setting forbids us to run third party actions in our Workflows (e.g. the docker build action)

Further down on the same page there should be 3 checkboxes regarding tokens and secrets. These you should check. 

> Access tokens on dockerhub
> 
> 
> 
> image

I don't think those are required. You should be able to safely remove them if you like. 

> Repository secrets:
> 
> 
> 
> image

Looks good. Thank you

**Comment by tdurand** [comment]
Okay, I reverted to "all actions" and I found the setting, it was under the organization settings and not repository settings, it is unchecked

image

Should be good now for a test ? Let me know

**Comment by vsaw** [comment]
@tdurand I believe this will disable actions for pull requests coming from forks such as mine. I recommend you select the following settings

image

This should allow us to run all the tests in pull requests (including testing a successful docker build) but not share the dockerhub secrets with forks. In this case pushing images to dockerhub will not work from pull request, but it will still work on new commits to the main Opendatacam repository using the "push" trigger for the workflow.

**Comment by tdurand** [comment]
Ok ! Done the same:

image

**Comment by vsaw** [comment]
I've just successfully published the first opendatacam docker image using GitHub actions 🎉 (to my personal Dockerhub account, but still 😎)

I've set up the workflow as follows:

- If run as pull request: Build Docker Image but do not publish
- If push to Opendatacam development branch: Build docker image and publish as Opendatacam
- If push to a forks development branch: Build docker image. If fork has their own `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` set, it will publish docker image under the forks credentials. See https://hub.docker.com/u/vsawdoteu/ as an example

**Comment by vsaw** [comment]
I could successfully run `vsawdoteu/opendatacam:development-nano` on my Jetson Nano. I don't have the necessary hardware to test the other builds but I'm confident they will work as well!

**Comment by vsaw** [comment]
@tdurand The documentation has been updated. Feel free to review. I would like you to do the merge as only you can remove faulty images from dockerhub in case something goes wrong.

**Comment by tdurand** [comment]
@vsaw congrats !! seems pretty clean to me ;-) 

the only thing I'm a bit "worried" about is that we will not be very sober in term of disk use on the dockerhub.. do you know if it is possible to just replace the latest development or somehow just erase legacy docker image that will be not tied to a release & not the latest development ?

+ also building all the image on each commit sounds not very sober in server CPU use , but I guess what we should do now it really respect the feature branches and merge to development real additional features / fixes so it doesn't build the things all the time.

Sorry for beeing picky, is it just that I try to see how to optimize a bit things and not waste too much ressources even if they are free to use 😁

Feel free to merge and let me know if you see something wrong I'm around in the next days.

**Review by tdurand — APPROVED** [review]

**Comment by vsaw** [comment]
Thanks for the review. 

The development images should be overwritten on every new build, so we should not take up to much new space.

As for the CPU usage, there are a few improvements we can do to reduce the build time as mentioned above. 

Given the low frequency of pull requests and changes to development I would not limit the execution of the workflow but rather invest into the performance improvements.

**Comment by tdurand** [comment]
> The development images should be overwritten on every new build, so we should not take up to much new space.

Great !

> As for the CPU usage, there are a few improvements we can do to reduce the build time as mentioned above.
> 
> Given the low frequency of pull requests and changes to development I would not limit the execution of the workflow but rather invest into the performance improvements.

Yes, let's not worry too much, also right now it is kind of in "heavy" development pace, but it will go down 😉

**Comment by tdurand** [comment]
🙌 well done !

**Pull request merged**
