### PR TITLE
Update colors.js

### PR DESCRIPTION
**Pull request by munsterlander**
The default color is black and the default font color is black.  As such, when you get this many counters out, you can not see the direction indicator or the delete button. So this just changes the default color to a soothing shade of grey.

### CODE REVIEW

**Comment by munsterlander** [comment]
I just saw there was an issue opened on this:  https://github.com/opendatacam/opendatacam/issues/239.  This PR just does the basic recommendation.  Funny we came to the same conclusion.

**Comment by vsaw** [comment]
@munsterlander I'm currently constrained on time. Would you mind uploading a screenshot of the new colors to see what this PR does. Then I'd be happy to merge :)

**Comment by munsterlander** [comment]
@vsaw Sure!  As you can see, when you run out of colors, this PR changes the default from black - where you couldn't see the direction or delete icons - to a grey where you can, but you can still see the lines on the screen clearly.

image

**Comment by vsaw** [comment]
Looks great. Merging!

**Pull request merged**
