### PR TITLE
Removed purge warnings

### PR DESCRIPTION
**Pull request by munsterlander**
Currently, when you build this branch, there is a warning regarding Tailwind not removing all unused CSS.  I have not gone through every component, but to suppress this warning, we simply need to add `purge: false`.  If we should in fact be purging specific files or directories, we can change this to an array providing those as documented here:  https://tailwindcss.com/docs/optimizing-for-production.

### CODE REVIEW

**Comment by munsterlander** [comment]
There is still one warning regarding the out-of-date browser that is related to the api docs, but I have chosen to not resolve it based on the issue I raised:  https://github.com/opendatacam/opendatacam/issues/476

**Comment by munsterlander** [comment]
Ok so resolved the issue.  Should I be creating new branches per commit / PR?

**Comment by vsaw** [comment]
Thanks a bunch for the fixes! There is some great stuff in there that id like to merge right away. 

My main concern however is the privacy statement. I would love to keep this around for a while to give people the opportunity to review and comment and on it. 

Therefore if possible please split the PR into multiple smaller ones, ideally one for each issue you address.

**Comment by munsterlander** [comment]
Will do. That was my thought as well.

**Pull request closed without merging**
